<?php
/*
*
* Author: Sherwin R. Terunez
* Contact: sherwinterunez@yahoo.com
*
* Description:
*
* App Module
*
* Date: November 13, 2015
*
*/

if(!defined('APPLICATION_RUNNING')) {
	header("HTTP/1.0 404 Not Found");
	die('access denied');
}

if(defined('ANNOUNCE')) {
	echo "\n<!-- loaded: ".__FILE__." -->\n";
}

global $applogin;

$toolbars['app']['main'] = 	array(
	array(	"id"=>"etap",
			"type"=>"button",
			"text"=>"eTap",
			"img"=>"tap.png",
			"imgdis"=>"tap.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "etap",
			"window" => true,
	),
	array(	"id"=>"newmessage",
			"type"=>"button",
			"text"=>"New Message",
			"img"=>"newmessage.png",
			"imgdis"=>"newmessage.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "newmessage",
			"window" => true,
	),
	array(	"id"=>"messaging",
			"type"=>"button",
			"text"=>"Messages",
			"img"=>"messages.png",
			"imgdis"=>"messages.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "messaging",
			"window" => true,
	),
	/*array(	"id"=>"message",
			"type"=>"button",
			"text"=>"Messages",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "message",
			"window" => true,
	),*/
	/*array(	"id"=>"survey",
			"type"=>"button",
			"text"=>"Survey",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "survey",
			"window" => true,
	),*/
	array(	"id"=>"contact",
			"type"=>"button",
			"text"=>"Contacts",
			"img"=>"contacts.png",
			"imgdis"=>"contacts.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "contact",
			"window" => true,
	),
	array(	"id"=>"group",
			"type"=>"button",
			"text"=>"Group",
			"img"=>"groups.png",
			"imgdis"=>"groups.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "group",
			"window" => true,
			//"action" => "formonly",
	),
	array(	"id"=>"report",
			"type"=>"button",
			"text"=>"Reports",
			"img"=>"reports.png",
			"imgdis"=>"reports.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "report",
			"window" => true,
	),
	array(	"id"=>"setting",
			"type"=>"button",
			"text"=>"Settings",
			"img"=>"settings.png",
			"imgdis"=>"settings.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "setting",
			"window" => true,
	),
	/*array(	"id"=>"backup",
			"type"=>"button",
			"text"=>"Backup",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "backup",
			"window" => true,
	),*/
	/*array(	"id"=>"help",
			"type"=>"button",
			"text"=>"Help",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "help",
			"window" => true,
	),*/
	/*array(	"id"=>"about",
			"type"=>"button",
			"text"=>"About",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "about",
			"window" => true,
	),*/
	/*array(	"id"=>"tnt",
			"type"=>"button",
			"text"=>"Tap N' Txt",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "tnt",
			"window" => true,
	),*/
	/*array(	"id"=>"promotion",
			"type"=>"button",
			"text"=>"Promotion",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "promotion",
	),*/
	/*array(	"id"=>"scheduler",
			"type"=>"button",
			"text"=>"Scheduler",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "scheduler",
	),*/
	/*array(	"id"=>"eload",
			"type"=>"button",
			"text"=>"E-Load",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "eload",
	),*/
	/*array(	"id"=>"referral",
			"type"=>"button",
			"text"=>"Referrals",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"module" => "referral",
	),*/
	array(	"id"=>"secure",
			"type"=>"buttonSelect",
			"text"=>"Security",
			"img"=>"security.png",
			"imgdis"=>"security.png",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"useraccount",
						"type"=>"obj",
						"text"=>"User Accounts",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"useraccount",
				),
		)
	),
	array(
		"id"=>"secure",
		"type"=>"spacer",
	),
	/*array(	"id"=>"utilities",
			"type"=>"buttonSelect",
			"text"=>"Utilities",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"usermanagement",
						"type"=>"obj",
						"text"=>"User Management",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"user",
				),
				array(
						"id"=>"utilitiessep1",
						"type"=>"separator",
				),
				array(	"id"=>"settings",
						"type"=>"obj",
						"text"=>"Settings",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
		)
	),
	array(
		"id"=>"utilities",
		"type"=>"spacer",
	),*/
	array(	"id"=>"title",
			"type"=>"text",
			"text"=>$applogin->fullname(),
	),
	array(	"id"=>"status",
			"type"=>"text",
			"text"=>"Checking Server Status...",
	),
	/*array(	"id"=>"start",
			"type"=>"button",
			"text"=>"Run",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"multiple" => false,
	),
	array(	"id"=>"stop",
			"type"=>"button",
			"text"=>"Stop",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"multiple" => false,
	),
	array(	"id"=>"scan",
			"type"=>"button",
			"text"=>"Scan Ports",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"multiple" => false,
	),*/
	array(	"id"=>"server",
			"type"=>"buttonSelect",
			"text"=>"Modem",
			"img"=>"modem.png",
			"imgdis"=>"modem.png",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"start",
						"type"=>"obj",
						"text"=>"Run",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
				array(	"id"=>"stop",
						"type"=>"obj",
						"text"=>"Pause",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
				array(	"id"=>"restart",
						"type"=>"obj",
						"text"=>"Restart",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
				array(	"id"=>"scan",
						"type"=>"obj",
						"text"=>"Scan Ports",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
		)
	),
	array(	"id"=>"computer",
			"type"=>"buttonSelect",
			"text"=>"Computer",
			"img"=>"computer.png",
			"imgdis"=>"computer.png",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"restartkiosk",
						"type"=>"obj",
						"text"=>"Restart Kiosk",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
				array(	"id"=>"reboot",
						"type"=>"obj",
						"text"=>"Reboot",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
				array(	"id"=>"poweroff",
						"type"=>"obj",
						"text"=>"Power Off",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
		)
	),
	array(	"id"=>"logout",
			"type"=>"button",
			"text"=>"Logout",
			"img"=>"logout.png",
			"imgdis"=>"logout.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"multiple" => false,
	),
);

if($applogin->isSysAdmin()&&checkLicense()&&isServerLicense()) {
	$toolbars['app']['main'][] = array(	"id"=>"management",
			"type"=>"buttonSelect",
			"text"=>"Management",
			"img"=>"security.png",
			"imgdis"=>"security.png",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"clients",
						"type"=>"obj",
						"text"=>"Clients",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"clients",
				),
		)
	);
}

/*
array(	"id"=>"management",
		"type"=>"buttonSelect",
		"text"=>"Management",
		"img"=>"security.png",
		"imgdis"=>"security.png",
		"title"=>"Tooltip here",
		"opts"=>array(
			array(	"id"=>"clients",
					"type"=>"obj",
					"text"=>"Clients",
					"img"=>"copy.gif",
					"imgdis"=>"copy.gif",
					"title"=>"Tooltip here",
					"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
					"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
					"tab_width" => 150,
					"multiple" => false,
					"module"=>"clients",
			),
	)
),
*/

$toolbars['app']['group'] = array(
	array(	"id"=>"groupedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"groupdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"groupsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"groupcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"grouprefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['setting'] = array(
	array(	"id"=>"settingedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"settingdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"settingsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"settingcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"settingrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['newmessage'] = array(
	array(	"id"=>"newmessageoutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"send.png",
			"imgdis"=>"send_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"newmessagenow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"send.png",
			"imgdis"=>"send_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"newmessageedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"newmessagedelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"newmessagesave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"newmessagecancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"newmessagerefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['message'] = array(
	array(	"id"=>"messageedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"messagedelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"messagesave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"messagecancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"messagerefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['survey'] = array(
	array(	"id"=>"surveyedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"surveydelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"surveysave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"surveycancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"surveyrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['contact'] = array(
	array(	"id"=>"contactnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"contactedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"contactdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"contactsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"contactcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"contactrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['report'] = array(
	array(	"id"=>"reportedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportexportpdf",
			"type"=>"button",
			"text"=>"Export PDF",
			"img"=>"pdf.png",
			"imgdis"=>"pdf_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportprint",
			"type"=>"button",
			"text"=>"Print",
			"img"=>"print.png",
			"imgdis"=>"print_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"reportprint",
			"type"=>"spacer",
	),
	array(	"id"=>"reportperiod",
			"type"=>"text",
			"text"=>"Period",
			"hidden"=>true,
	),
	array(	"id"=>"reportfrom",
			"type"=>"text",
			"text"=>"From",
			"hidden"=>true,
	),
	array(	"id"=>"reportdatefrom",
			"type"=>"input",
			"text"=>"From",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportto",
			"type"=>"text",
			"text"=>"To",
			"hidden"=>true,
	),
	array(	"id"=>"reportdateto",
			"type"=>"input",
			"text"=>"To",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportfilter",
			"type"=>"button",
			"text"=>"Filter",
			//"img"=>"copy.gif",
			//"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['backup'] = array(
	array(	"id"=>"backupedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"backupdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"backupsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"backupcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"backuprefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['help'] = array(
	array(	"id"=>"helpedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"helpdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"helpsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"helpcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"helprefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['about'] = array(
	array(	"id"=>"aboutedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"aboutdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"aboutsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"aboutcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"aboutrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['usermanagement'] = array(
	array(	"id"=>"usermanagementnewroles",
			"type"=>"button",
			"text"=>"New Role",
			"img"=>"newrole.png",
			"imgdis"=>"newrole.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementnewuser",
			"type"=>"button",
			"text"=>"New User",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['useraccount'] = array(
	array(	"id"=>"useraccountnewrole",
			"type"=>"button",
			"text"=>"New Role",
			"img"=>"newrole.png",
			"imgdis"=>"newrole.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountnewuser",
			"type"=>"button",
			"text"=>"New User",
			"img"=>"newuser.png",
			"imgdis"=>"newuser.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['messaging'] = 	array(
	array(	"id"=>"messagingsendtooutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsendnow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsendstart",
			"type"=>"button",
			"text"=>"Start",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsendstop",
			"type"=>"button",
			"text"=>"Stop",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingcomposeto",
			"type"=>"button",
			"text"=>"Compose to",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingclone",
			"type"=>"button",
			"text"=>"Clone",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingresend",
			"type"=>"button",
			"text"=>"Resend",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingaddcontact",
			"type"=>"button",
			"text"=>"Add Contact",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingreply",
			"type"=>"button",
			"text"=>"Reply",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingforward",
			"type"=>"button",
			"text"=>"Forward",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingclear",
			"type"=>"button",
			"text"=>"Clear",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingimport",
			"type"=>"button",
			"text"=>"Import",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingexport",
			"type"=>"button",
			"text"=>"Export",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingoptions",
			"type"=>"button",
			"text"=>"Options",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messaginginsertrow",
			"type"=>"button",
			"text"=>"Insert Row",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingdetails",
			"type"=>"button",
			"text"=>"Details",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['promotion'] = 	array(
	array(	"id"=>"promotionsendtooutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionsendnow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionresend",
			"type"=>"button",
			"text"=>"Resend",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotiondelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionclear",
			"type"=>"button",
			"text"=>"Clear",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotioncancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotionrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"promotiondetails",
			"type"=>"button",
			"text"=>"Details",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['eload'] = 	array(
	array(	"id"=>"eloadbalance",
			"type"=>"button",
			"text"=>"Balance",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadproducts",
			"type"=>"button",
			"text"=>"Products",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadsendtooutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadsendnow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadresend",
			"type"=>"button",
			"text"=>"Resend",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadsend",
			"type"=>"button",
			"text"=>"Send",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloaddelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadclear",
			"type"=>"button",
			"text"=>"Clear",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloadrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"eloaddetails",
			"type"=>"button",
			"text"=>"Details",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['referral'] = 	array(
	array(	"id"=>"referralsettemplate",
			"type"=>"button",
			"text"=>"Set as Template",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralsendtooutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralsendnow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralresend",
			"type"=>"button",
			"text"=>"Resend",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referraledit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referraldelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralclear",
			"type"=>"button",
			"text"=>"Clear",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referralrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"referraldetails",
			"type"=>"button",
			"text"=>"Details",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['scheduler'] = 	array(
	array(	"id"=>"schedulersettemplate",
			"type"=>"button",
			"text"=>"Set as Template",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulersendtooutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulersendnow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulersend",
			"type"=>"button",
			"text"=>"Send",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulerresend",
			"type"=>"button",
			"text"=>"Resend",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulernew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"new.png",
			"imgdis"=>"new_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"scheduleredit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulerdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"delete.png",
			"imgdis"=>"delete_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulersave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulerclear",
			"type"=>"button",
			"text"=>"Clear",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulercancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"cancel.png",
			"imgdis"=>"cancel_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulerrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"refresh.png",
			"imgdis"=>"refresh_dis.png",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"schedulerdetails",
			"type"=>"button",
			"text"=>"Details",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);
